### ISSUE TITLE
too many bytes to write to stream error

### ISSUE THREAD

**Issue by MaliWhiteTea** [faketunaPrivateCamp/SkriptWebAPI#12]
When the server response the request, it is giving an error:

skript:

```
command /webbaşlat:
  trigger:
    start http server in port 25000 with context "/test/"

on http request received:
    set {_request} to event-httpexchange
    set {_method} to http request method of {_request}
    set {_body} to http request body of {_request}
    set {_userAgent} to http request {_request} request header value from key "User-Agent"
    set {_path} to http request context path of {_request}
    broadcast "HTTP REQUEST!"
    broadcast "METHOD: %{_method}%"
    broadcast "BDOY: %{_body}%"
    broadcast "UA: %{_userAgent}%"
    broadcast "Context: %{_path}%"
    
    reply {_request} with body "%{web::ad1::value::*}%" and response code 2100
    exit
on web request response:
    set {_response} to event-httpresponse
    set {_body} to body of {_response}
    set {_method} to request method of {_response}
    broadcast " "
    broadcast "server: %{_response}'s header value from key "server"%"
    broadcast "1: %{_body}%"
    broadcast "2: %status code of {_response}%"
    broadcast "3: %request method of {_response}%"   
on kci container action "ad1":
  if {web::ad1::%player%} is 1:
    set {web::ad1::%player%} to 1
    set {_randominteger} to random integer between 10000 and 999999999999999999
    delete {web::ad1::value::%player%}
    set {web::ad1::value::%player%} to "Odulunuzu Almak Icın Bu Komudu Kullanin: /reklamkodugir %player% %{_randominteger}%"
    send "<url:https://bit.ly/MNAD-1>&a&l[Reklam İçin Tıkla!]<reset>" to player

  if {web::ad1::%player%} is not set:
    set {web::ad1::%player%} to 1
    send "<url:https://bit.ly/MNAD-1>&a&l[Reklam İçin Tıkla!]<reset>" to player   
command /reklamkodugir [<text>] [<text>]:
  trigger:
    if {web::ad1::%player%} is 1:
      if arg-1 is "%player%":
        if arg-2 is {web::ad1::value::%player%}:
          
          set {web::ad1::%player%} to 0 
    send {web::ad1::%player%} to player
    send {web::ad1::value::%player%} to player          

```

error log:

```
[18:52:13 INFO]: MaliWhiteTea issued server command: /sk reload web.sk
[18:52:19 INFO]: HTTP REQUEST!
[18:52:19 INFO]: METHOD: GET
[18:52:19 INFO]: BDOY:
[18:52:19 INFO]: UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 OPR/107.0.0.0 (Edition std-1)
[18:52:19 INFO]: Context: /test/
[18:52:19 INFO]: [Skript]     An error occurred while send response to request!
[18:52:19 ERROR]: #!#!
[18:52:19 ERROR]: #!#! [Skript] Severe Error:
[18:52:19 ERROR]: #!#!
[18:52:19 ERROR]: #!#! You're running outdated version of Skript! Please try updating it NOW; it might fix this.
[18:52:19 ERROR]: #!#! Run /sk update check to get a download link to latest Skript!
[18:52:19 ERROR]: #!#! You will be given instructions how to report this error if it persists after update.
[18:52:19 ERROR]: #!#!
[18:52:19 ERROR]: #!#! Stack trace:
[18:52:19 ERROR]: #!#! java.lang.RuntimeException: java.io.IOException: too many bytes to write to stream
[18:52:19 ERROR]: #!#!     at SkriptWebAPI-0.1.1.jar//dev.f2a.addon.skriptwebapi.elements.server.effects.EffSendHttpResponse.execute(EffSendHttpResponse.java:62)
[18:52:19 ERROR]: #!#!     at Skript2.8.0.jar//ch.njol.skript.lang.Effect.run(Effect.java:49)
[18:52:19 ERROR]: #!#!     at Skript2.8.0.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[18:52:19 ERROR]: #!#!     at Skript2.8.0.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[18:52:19 ERROR]: #!#!     at Skript2.8.0.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[18:52:19 ERROR]: #!#!     at Skript2.8.0.jar//ch.njol.skript.SkriptEventHandler.lambda$check$3(SkriptEventHandler.java:155)
[18:52:19 ERROR]: #!#!     at Skript2.8.0.jar//ch.njol.skript.SkriptEventHandler.lambda$check$4(SkriptEventHandler.java:166)
[18:52:19 ERROR]: #!#!     at Skript2.8.0.jar//ch.njol.skript.util.Task.callSync(Task.java:164)
[18:52:19 ERROR]: #!#!     at Skript2.8.0.jar//ch.njol.skript.util.Task.callSync(Task.java:148)
[18:52:19 ERROR]: #!#!     at Skript2.8.0.jar//ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:164)
[18:52:19 ERROR]: #!#!     at Skript2.8.0.jar//ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:53)
[18:52:19 ERROR]: #!#!     at Skript2.8.0.jar//ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:66)
[18:52:19 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
[18:52:19 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[18:52:19 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[18:52:19 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[18:52:19 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[18:52:19 ERROR]: #!#!     at SkriptWebAPI-0.1.1.jar//dev.f2a.addon.skriptwebapi.internal.http.SkebHttpServer$SkebHttpHandler.lambda$handle$0(SkebHttpServer.java:52)
[18:52:19 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftFuture.run(CraftFuture.java:88)
[18:52:19 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[18:52:19 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1479)
[18:52:19 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
[18:52:19 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1393)
[18:52:19 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1170)
[18:52:19 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[18:52:19 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[18:52:19 ERROR]: #!#! Caused by: java.io.IOException: too many bytes to write to stream
[18:52:19 ERROR]: #!#!     at jdk.httpserver/sun.net.httpserver.FixedLengthOutputStream.write(FixedLengthOutputStream.java:79)
[18:52:19 ERROR]: #!#!     at java.base/java.io.FilterOutputStream.write(FilterOutputStream.java:108)
[18:52:19 ERROR]: #!#!     at jdk.httpserver/sun.net.httpserver.PlaceholderOutputStream.write(ExchangeImpl.java:459)
[18:52:19 ERROR]: #!#!     at SkriptWebAPI-0.1.1.jar//dev.f2a.addon.skriptwebapi.elements.server.effects.EffSendHttpResponse.execute(EffSendHttpResponse.java:58)
[18:52:19 ERROR]: #!#!     at Skript2.8.0.jar//ch.njol.skript.lang.Effect.run(Effect.java:49)
[18:52:19 ERROR]: #!#!     at Skript2.8.0.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[18:52:19 ERROR]: #!#!     at Skript2.8.0.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[18:52:19 ERROR]: #!#!     at Skript2.8.0.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[18:52:19 ERROR]: #!#!     at Skript2.8.0.jar//ch.njol.skript.SkriptEventHandler.lambda$check$3(SkriptEventHandler.java:155)
[18:52:19 ERROR]: #!#!     at Skript2.8.0.jar//ch.njol.skript.SkriptEventHandler.lambda$check$4(SkriptEventHandler.java:166)
[18:52:19 ERROR]: #!#!     at Skript2.8.0.jar//ch.njol.skript.util.Task.callSync(Task.java:164)
[18:52:19 ERROR]: #!#!     at Skript2.8.0.jar//ch.njol.skript.util.Task.callSync(Task.java:148)
[18:52:19 ERROR]: #!#!     at Skript2.8.0.jar//ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:164)
[18:52:19 ERROR]: #!#!     at Skript2.8.0.jar//ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:53)
[18:52:19 ERROR]: #!#!     at Skript2.8.0.jar//ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:66)
[18:52:19 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
[18:52:19 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[18:52:19 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[18:52:19 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[18:52:19 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[18:52:19 ERROR]: #!#!     at SkriptWebAPI-0.1.1.jar//dev.f2a.addon.skriptwebapi.internal.http.SkebHttpServer$SkebHttpHandler.lambda$handle$0(SkebHttpServer.java:52)
[18:52:19 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftFuture.run(CraftFuture.java:88)
[18:52:19 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[18:52:19 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1479)
[18:52:19 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
[18:52:19 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1393)
[18:52:19 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1170)
[18:52:19 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[18:52:19 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[18:52:19 ERROR]: #!#!
[18:52:19 ERROR]: #!#! Version Information:
[18:52:19 ERROR]: #!#!   Skript: 2.8.0 (OUTDATED)
[18:52:19 ERROR]: #!#!     Flavor: skriptlang-github
[18:52:19 ERROR]: #!#!     Date: 18:20:11.223179900
[18:52:19 ERROR]: #!#!   Bukkit: 1.20.1-R0.1-SNAPSHOT
[18:52:19 ERROR]: #!#!   Minecraft: 1.20.1
[18:52:19 ERROR]: #!#!   Java: 18.0.2.1 (Java HotSpot(TM) 64-Bit Server VM 18.0.2.1+1-1)
[18:52:19 ERROR]: #!#!   OS: Windows Server 2019 amd64 10.0
[18:52:19 ERROR]: #!#!
[18:52:19 ERROR]: #!#! Server platform: Paper
[18:52:19 ERROR]: #!#!
[18:52:19 ERROR]: #!#! Current node: null
[18:52:19 ERROR]: #!#! Current item:
[18:52:19 ERROR]: #!#! Current trigger: http request received () (web.sk, line 5)
[18:52:19 ERROR]: #!#!
[18:52:19 ERROR]: #!#! Thread: Server thread
[18:52:19 ERROR]: #!#!
[18:52:19 ERROR]: #!#! Language: turkish
[18:52:19 ERROR]: #!#! Link parse mode: DISABLED
[18:52:19 ERROR]: #!#!
[18:52:19 ERROR]: #!#! End of Error.
[18:52:19 ERROR]: #!#!
[18:53:51 WARN]: Can't keep up! Is the server overloaded? Running 5274ms or 105 ticks behind
```

**Comment by faketuna** [comment]
Hello, Thank you for bug reporting!

If you can, I want to know theese information!
* The body what you trying to send in http response

**Comment by faketuna** [comment]
Also, I maybe fixed this issue. Please try test version of my plugin.
[SkriptWebAPI-0.1.1-issue-12.jar.zip](https://github.com/faketunaPrivateCamp/SkriptWebAPI/files/14625505/SkriptWebAPI-0.1.1-issue-12.jar.zip)

**Comment by MaliWhiteTea** [comment]
I just use `set {web::ad1::value::%player%} to "Odulunuzu Almak Icın Bu Komudu Kullanin: /reklamkodugir %player% %{_randominteger}%"` for `{web::ad1::value::*}`.

Is it a wrong use?

Im trying the new version of plugin that you sent now

**Comment by MaliWhiteTea** [comment]
The new version of the plugin is works now. But i have another question now: How can i use \n ? 
![image](https://github.com/faketunaPrivateCamp/SkriptWebAPI/assets/118561035/507f763e-87d1-4124-ba2f-ef27135d8599)
![image](https://github.com/faketunaPrivateCamp/SkriptWebAPI/assets/118561035/8833e778-3e52-42ad-a2a6-a6c8eae967d7)

**Comment by faketuna** [comment]
> I just use `set {web::ad1::value::%player%} to "Odulunuzu Almak Icın Bu Komudu Kullanin: /reklamkodugir %player% %{_randominteger}%"` for `{web::ad1::value::*}`.
> 
> Is it a wrong use?
> 
> Im trying the new version of plugin that you sent now

No. You are doing correctly! My plugin is doing wrong when sending response.



> The new version of the plugin is works now. But i have another question now: How can i use \n ? ![image](https://private-user-images.githubusercontent.com/118561035/313503394-507f763e-87d1-4124-ba2f-ef27135d8599.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MjA3MjAsIm5iZiI6MTcxMDcyMDQyMCwicGF0aCI6Ii8xMTg1NjEwMzUvMzEzNTAzMzk0LTUwN2Y3NjNlLTg3ZDEtNDEyNC1iYTJmLWVmMjcxMzVkODU5OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQwMDA3MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZjE5MDFmMDI2NzIyODRlMThiMTYzMzNlMjRjYjQ1MmNjODQxZjkxOTM1ZjM0NjY3ZmQ0MzFkZGQwYzM5MzhkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KJlWAWDdP68FCy-fx5L1VuXd8nc26B__02hNo0MlyW8) ![image](https://private-user-images.githubusercontent.com/118561035/313503410-8833e778-3e52-42ad-a2a6-a6c8eae967d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MjA3MjAsIm5iZiI6MTcxMDcyMDQyMCwicGF0aCI6Ii8xMTg1NjEwMzUvMzEzNTAzNDEwLTg4MzNlNzc4LTNlNTItNDJhZC1hMmE2LWE2YzhlYWU5NjdkNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQwMDA3MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NWNiZTk1MWVmZTkwMWQ0M2FiNDc2ZTdhOThkOTNiYmYyNGE0ODU1ZTBlOTk1YmZlMjZjM2NlNTA5OWRjMWQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.G__DYb3EfZT62N9yq74L6-7hXhEWpIpn_pI0ptl3YUs)

You can use [New Line Expression](https://docs.skriptlang.org/docs.html?search=#LitNewLine) provided in skript.
Expression s are:
- %nl%
- %newline%
- %line break%
- %linebreak%
for example...
```
set {_test} to "This is line 1 %nl% This is line 2"
```

**Comment by MaliWhiteTea** [comment]
It works. Thanks for %nl% info. I didnt know it. But can i remove the `and`?

![image](https://github.com/faketunaPrivateCamp/SkriptWebAPI/assets/118561035/5b857859-23ba-4060-956b-fd2c42b3669e)

**Comment by MaliWhiteTea** [comment]
By the way, can you support non-english characters? For example when i try to use a Turkish character like `ı, ğ, Ğ, ü, Ü, ş, Ş, İ, ö, Ö, ç, Ç`, the text seems weird:

![image](https://github.com/faketunaPrivateCamp/SkriptWebAPI/assets/118561035/c66630ff-3a80-4663-9d3d-e830e05a6d10)

` %nl%Ödülünüzü Almak İçin Bu Komudu Kullanın: /reklamkodugir %player% %{_randominteger}%`

**Comment by MaliWhiteTea** [comment]
And can i get the IP adress of requester in Skript?

**Comment by faketuna** [comment]
> It works. Thanks for %nl% info. I didnt know it. But can i remove the `and`?
> 
> ![image](https://private-user-images.githubusercontent.com/118561035/313541812-5b857859-23ba-4060-956b-fd2c42b3669e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NjE3MzMsIm5iZiI6MTcxMDc2MTQzMywicGF0aCI6Ii8xMTg1NjEwMzUvMzEzNTQxODEyLTViODU3ODU5LTIzYmEtNDA2MC05NTZiLWZkMmM0MmIzNjY5ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQxMTMwMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OWFhNjY5YzEwN2U0NTA4ZWQ4NGM2ZGE3Y2VmNWJkNjQxMDAyNjQyZGFkYWVmZmJiMzM5NmIwYzdjYzkzMmY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yHN1Vqfohbg8W-rM_eFG4XIvMFDuFHsV8BrD_vshIRU)

When you parse list to text, it will be appear the "and" and "," in text.
you can remove these with [replace expression](https://docs.skriptlang.org/docs.html?search=#EffReplace)
e.g.`replace all "and" in {_variable} with ""`

Also sorry, this place is should talk about the first post in this issue. so please ask general skript question at skunity discord or something community.

> By the way, can you support non-english characters? For example when i try to use a Turkish character like `ı, ğ, Ğ, ü, Ü, ş, Ş, İ, ö, Ö, ç, Ç`, the text seems weird:
  > 
  > ![image](https://private-user-images.githubusercontent.com/118561035/313542495-c66630ff-3a80-4663-9d3d-e830e05a6d10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NjE3MzMsIm5iZiI6MTcxMDc2MTQzMywicGF0aCI6Ii8xMTg1NjEwMzUvMzEzNTQyNDk1LWM2NjYzMGZmLTNhODAtNDY2My05ZDNkLWU4MzBlMDVhNmQxMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQxMTMwMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MjBiNWZhOTdjODJjMjA4MTlkODQ1MWIxNmY3M2U2NWZjY2E3NzZkODc4ZWRkYmM2ZWMyNGQ0ZDRmMDcxMzgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QEDYe8PfaEOa4B0Zd9AzgdepE8VPkyA5D49uxZlLBrE)
  > 
  > ` %nl%Ödülünüzü Almak İçin Bu Komudu Kullanın: /reklamkodugir %player% %{_randominteger}%`

Umm... It should work properly with multibyte characters because I'm using with japanese and works well.

This content is different from the current Issue. so lets discuss this in a new issue https://github.com/faketunaPrivateCamp/SkriptWebAPI/issues/14

> And can i get the IP adress of requester in Skript?

It's not implemented yet, Ill support later. see https://github.com/faketunaPrivateCamp/SkriptWebAPI/issues/13
