### ISSUE TITLE
purpur 1.17.1で起動に失敗する(Unsupported API version 1.19)

### ISSUE THREAD

**Issue by ringo360** [faketunaPrivateCamp/SkriptWebAPI#7]
**Describe the bug**
purpur-1.17.1 (build 1428)でSkriptWebAPIを読み込むことができません。

**Error log**
```
[10:41:07 ERROR]: Could not load 'plugins/SkriptWebAPI-0.0.3b.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.19
        at org.bukkit.craftbukkit.v1_17_R1.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:358) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:149) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:414) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:322) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:419) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:322) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1233) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-1428]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
**To Reproduce**
1. Go [PurpurMC Download Page](https://purpurmc.org/downloads/1.17.1)
2. Download [last build](https://api.purpurmc.org/v2/purpur/1.17.1/1428/download)
3. Start Server

**Expected behavior**
通常通りに起動し、`/sk info`でアドオンとして読み込まれている事を確認できる。

**Screenshots**
無し

**Additional context**
無し

**Comment by ringo360** [comment]
Dev aren't working... 💀

**Comment by faketuna** [comment]
返信が大変遅くなりすいません！！
この問題の解決方法なのですが、プラグインの最低APIバージョンが1.19に設定されていることが原因のため、ご自身でBuildが可能な場合は以下の点を1.16や1.17等に書き換えて頂いた後にbuildをしていただくと指定したバージョン以上で起動するプラグインのJarファイルが生成されます。
https://github.com/faketunaPrivateCamp/SkriptWebAPI/blob/502f97ec14329ce2eb11772358901fe978a2815f/build.gradle.kts#L33

一応1.19以下のMinecraftバージョンでもロードできるようにしたバージョンをリリースします。

1.19以下での動作は未確認であることと、Skript 2.7リリース前からこのプラグインをメンテナンスしていないためバグが発生する可能性があります。その点はご了承ください。

**Comment by faketuna** [comment]
1.13以降で**恐らく**ロードできるバージョンを作成しました。
[ここからDLできます](https://github.com/faketunaPrivateCamp/SkriptWebAPI/releases/tag/v0.0.4)

もし動作しなかった場合は新しくIssueを立てていただくと助かります。

**Comment by ringo360** [comment]
動作しました ✅ 
ありがとうございます 🙏
